version: "3.8"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  db:
    container_name: 'univesp_donation'
    restart: always
    image: mysql:latest
    command: --authentication_policy=mysql_native_password
    ports:
      - '3308:3306'
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASS: 'root'
      MYSQL_DATABASE: db_univesp_donation
    cap_add:
      - SYS_NICE
